name: Sync pfQuest Updates

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:       # Manual trigger

permissions:
  contents: write  # Required to push commits and tags

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 3. Add upstream remote
      - name: Add upstream
        run: |
          git remote add upstream https://github.com/Bennylavaa/pfQuest-epoch.git || true
          git fetch upstream

      # 4. Check for new commits
      - name: Check for new commits
        id: check
        run: |
          git checkout main
          git log upstream/main --not main --oneline > new_commits.txt || true
          if [ -s new_commits.txt ]; then
            echo "new_updates=true" >> $GITHUB_ENV
          else
            echo "new_updates=false" >> $GITHUB_ENV
          fi

      # 5. Merge updates, create tag
      - name: Merge updates & tag
        if: env.new_updates == 'true'
        run: |
          git checkout main
          # Merge upstream changes
          git merge upstream/main --allow-unrelated-histories -m "Merge upstream updates" || { echo "Merge failed"; exit 1; }
          # Create a timestamped tag
          TAG=v$(date +'%Y.%m.%d-%H%M')
          git tag $TAG
          # Push commits and tags
          git push origin main
          git push origin --tags
          echo "TAG=$TAG" >> $GITHUB_ENV

      # 6. Send Discord Notification
      - name: Send Discord Notification
        if: env.new_updates == 'true'
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"username\":\"Addon Sync Bot\",\"embeds\":[{\"title\":\"pfQuest Updates Detected\",\"description\":\"New upstream updates were merged from [Bennylavaa/pfQuest-epoch](https://github.com/Bennylavaa/pfQuest-epoch).\",\"color\":3066993}]}" \
               ${{ secrets.DISCORD_WEBHOOK }}
